baseURL = "/"
languageCode = "en-us"
title = "Canary"
theme = "ezhil"
paginate = 5

copyright = "© 2019 Canary"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""
disqusShortname = ""

[params]
	subtitle = "A member of the updated tilde.club. "
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
    favicon = "https://tilde.club/~canary/favicon.png"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:canary@tilde.club"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/gohugoio"

[[params.social]]
name = "RSS"
icon = "rss"
url = "https://tilde.club/~canary/index.xml"

[taxonomies]
   tag = "tags"
